import { PrintDetailView, FilamentPrintsView, PrinterPrintsView } from './mockprints.service'

export const PRINTS: PrintDetailView[] = [
    // represents a returned VIEW. Not necessarily the entity
    {PrintId: 1, 
        Name: "3D Benchy", 
        SourceUrl: "http://www.thingiverse.com/thing:763622", 
        ModelPath: "", 
        Success: true,
        PrintTimeHours: 2, 
        PrintTimeMinutes: 5, 
        MainPrintImageUrl: "assets/images/benchy.JPG", 
        FilamentName: "Hatchbox PLA (Gray) - Spool 3", 
        PrinterName:"Maker Select - Printer 1", 
        UserId:2,
        ModelFileUrl: undefined,
        LengthUsed: 45,
        Date: new Date("4/11/2017"),
        PrintConfigId: 1},
    {PrintId: 2, 
        Name: "Fidget spinner", 
        SourceUrl: "http://www.thingiverse.com/thing:763622", 
        ModelPath: "", 
        Success: true,
        PrintTimeHours: 2, 
        PrintTimeMinutes: 5, 
        MainPrintImageUrl: "assets/images/benchy.JPG", 
        FilamentName: "Hatchbox PLA (Gray) - Spool 3", 
        PrinterName:"Maker Select - Printer 1", 
        UserId:2,
        ModelFileUrl: "test/test/test",
        LengthUsed: 45,
        Date: new Date("4/11/2017"),
        PrintConfigId: 1},
    {PrintId: 3, 
        Name: "Baby groot", 
        SourceUrl: "http://www.thingiverse.com/thing:763622", 
        ModelPath: "", 
        Success: true,
        PrintTimeHours: 2, 
        PrintTimeMinutes: 5, 
        MainPrintImageUrl: "assets/images/benchy.JPG", 
        FilamentName: "Hatchbox PLA (Gray) - Spool 3", 
        PrinterName:"Maker Select - Printer 1", 
        UserId:1,
        ModelFileUrl: "test/test/test",
        LengthUsed: 45,
        Date: new Date("4/11/2017"),
        PrintConfigId: 1},
    {PrintId: 4, 
        Name: "Spool Holder", 
        SourceUrl: "http://www.thingiverse.com/thing:763622", 
        ModelPath: "", 
        Success: true,
        PrintTimeHours: 2, 
        PrintTimeMinutes: 5, 
        MainPrintImageUrl: "assets/images/benchy.JPG", 
        FilamentName: "Inland PETG (Black) - Spool 4", 
        PrinterName:"Maker Select - Printer 1", 
        UserId:1,
        ModelFileUrl: "test/test/test",
        LengthUsed: 45,
        Date: new Date("4/11/2017"),
        PrintConfigId: 1},
    {PrintId: 5, 
        Name: "Ninja Stars", 
        SourceUrl: "http://www.thingiverse.com/thing:763622", 
        ModelPath: "", 
        Success: true,
        PrintTimeHours: 2, 
        PrintTimeMinutes: 5, 
        MainPrintImageUrl: "assets/images/benchy.JPG", 
        FilamentName: "Monoprice PLA (White) - Spool 1", 
        PrinterName: "Maker Select - Printer 1", 
        UserId:1,
        ModelFileUrl: "test/test/test",
        LengthUsed: 45,
        Date: new Date("4/11/2017"),
        PrintConfigId: undefined}   
]

export const FILAMENTSPRINTSLIBRARYVIEW: FilamentPrintsView[] = [
    {Name: "Monoprice PLA (White) - Spool 1", UserId: 1, FilamentId: 1},
    {Name: "Hatchbox PLA (Gray) - Spool 3", UserId: 1, FilamentId: 2},
    {Name: "Inland PETG (Black) - Spool 4", UserId: 2, FilamentId: 3}
]

export const PRINTERSPRINTSLIBRARYVIEW: PrinterPrintsView[] = [
    {Name: "Maker Select - Printer 1", UserId: 1, PrinterId: 1}
]