import { PrinterDetailView, PrinterLibraryView, PrintPrinterView } from './mockprinters.service';

export const PRINTERDETAILS: PrinterDetailView[] = [
    {PrinterId: 1,
        UserId: 1,
        Name: "Monoprice Maker Select",
        NumberOfPrints: 10,
        DateAcquired: new Date("4/12/2016"),
        Source: "Newegg",
        BeltMaintInt: 100,
        BeltMaintLast: 325,
        LubeMaintInt: 100,
        LubeMaintLast: 325,
        WireMaintInt: 100,
        WireMaintLast: 325,
        PrintTimeHours: 400,
        MainPrinterImageUrl: "assets/images/makerselect.jpg",
        UserPrinterId: 1,
        Prints: [ 
            { PrintId: 1, Name: "3D Benchy", MainPrintImageUrl: "assets/images/benchy.JPG"}, 
            { PrintId: 2, Name: "Fidget Spinner", MainPrintImageUrl: "assets/images/benchy.JPG"}
        ]
    },
    {PrinterId: 2,
        UserId: 1,
        Name: "Lulzbot TAZ6",
        NumberOfPrints: 10,
        DateAcquired: new Date("4/12/2016"),
        Source: "Newegg",
        BeltMaintInt: 100,
        BeltMaintLast: 325,
        LubeMaintInt: 100,
        LubeMaintLast: 325,
        WireMaintInt: 100,
        WireMaintLast: 325,
        PrintTimeHours: 400,
        MainPrinterImageUrl: "assets/images/makerselect.jpg",
        UserPrinterId: 2,
        Prints: undefined
    },
    {PrinterId: 6,
        UserId: 1,
        Name: "Wanhao Duplicator",
        NumberOfPrints: 10,
        DateAcquired: new Date("4/12/2016"),
        Source: "Newegg",
        BeltMaintInt: 100,
        BeltMaintLast: 325,
        LubeMaintInt: 100,
        LubeMaintLast: 325,
        WireMaintInt: 100,
        WireMaintLast: 325,
        PrintTimeHours: 400,
        MainPrinterImageUrl: "assets/images/makerselect.jpg",
        UserPrinterId: 3,
        Prints: undefined
    },
]

export const PRINTERLIBRARY: PrinterLibraryView[] = [
    {PrinterId: 1,
        UserId: 1,
        Name: "Monoprice Maker Select",
        NumberOfPrints: 10,
        DateAcquired: new Date("4/12/2016"),
        PrintTimeHours: 400,
        MainPrinterImageUrl: "assets/images/makerselect.jpg",
        UserPrinterId: 1
    },
    {PrinterId: 2,
        UserId: 1,
        Name: "Lulzbot TAZ6",
        NumberOfPrints: 10,
        DateAcquired: new Date("4/12/2016"),
        PrintTimeHours: 400,
        MainPrinterImageUrl: "assets/images/makerselect.jpg",
        UserPrinterId: 2
    },
    {PrinterId: 6,
        UserId: 1,
        Name: "Wanhao Duplicator",
        NumberOfPrints: 10,
        DateAcquired: new Date("4/12/2016"),
        PrintTimeHours: 400,
        MainPrinterImageUrl: "assets/images/makerselect.jpg",
        UserPrinterId: 3
    },

]